M48
; DRILL file KiCad 10.0.5 date 2026-08-09T14:18:47
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-09T14:18:47+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.092
%
G90
G05
T1
X57.76Y-61.81
X57.76Y-67.59
T2
X44.347Y-76.453
X55.347Y-76.453
M30
